_target_: litmodule.LitALI

ali:
  _target_: model.ALI
  enc:
    _target_: model.encoder.CIFAR10Encoder
  dec:
    _target_: model.decoder.CIFAR10Decoder
  dis:
    _target_: model.discriminator.CIFAR10Discriminator