_target_: litmodule.LitALI

ali:
  _target_: model.ALI
  enc:
    _target_: model.encoder.MNISTEncoder
  dec:
    _target_: model.decoder.MNISTDecoder
  dis:
    _target_: model.discriminator.MNISTDiscriminator